# Generated by Django 3.1.2 on 2021-02-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigndriver',
            old_name='vehicleId',
            new_name='vehicleid',
        ),
    ]
