# Generated by Django 3.1.2 on 2020-11-28 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('license_no', models.CharField(max_length=50)),
                ('no_of_gears', models.CharField(max_length=1)),
                ('no_of_seats', models.CharField(max_length=1)),
                ('category', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
