# Generated by Django 3.1.2 on 2021-02-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210209_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervehicle',
            name='service',
            field=models.CharField(max_length=50),
        ),
    ]
