# Generated by Django 3.1.2 on 2021-02-19 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210209_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_booking', models.CharField(max_length=12)),
                ('starting_date', models.CharField(max_length=12)),
                ('pick_up_time', models.CharField(max_length=8)),
                ('pick_up_province', models.IntegerField(null=True)),
                ('pick_up_disctrict', models.CharField(max_length=30, null=True)),
                ('pick_up_city', models.CharField(max_length=30, null=True)),
                ('pick_up_street', models.CharField(max_length=50, null=True)),
                ('destination_province', models.IntegerField(null=True)),
                ('destination_disctrict', models.CharField(max_length=30, null=True)),
                ('destination_city', models.CharField(max_length=30, null=True)),
                ('number_of_days', models.IntegerField(null=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assigndriver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registervehicle')),
            ],
        ),
    ]
