# Generated by Django 3.1.2 on 2021-01-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210105_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registervehicle',
            old_name='license_no',
            new_name='licenseNumber',
        ),
    ]
