# Generated by Django 3.1.2 on 2021-01-13 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210105_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverName', models.CharField(max_length=100)),
                ('driverAddress', models.CharField(max_length=100)),
                ('driverContact', models.CharField(max_length=20)),
                ('licenseImage', models.ImageField(default='Blank', upload_to='')),
                ('vehicleId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.registervehicle')),
            ],
        ),
    ]
