# Generated by Django 3.1.2 on 2021-02-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210219_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='starting_date',
            new_name='pick_up_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_of_booking',
            field=models.DateField(auto_now_add=True),
        ),
    ]
