# Generated by Django 3.1.2 on 2021-02-21 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210221_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='destination_disctrict',
            new_name='destination_district',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='pick_up_disctrict',
            new_name='pick_up_district',
        ),
    ]
