# Generated by Django 3.1.2 on 2021-01-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_assigndriver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigndriver',
            name='driverContact',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='registervehicle',
            name='licenseNumber',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
