# Generated by Django 3.1.2 on 2021-03-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210221_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination_street',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination_city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination_district',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pick_up_city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pick_up_district',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pick_up_street',
            field=models.CharField(default='', max_length=50),
        ),
    ]
