# Generated by Django 3.1.2 on 2021-03-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pick_up_date',
            field=models.DateField(),
        ),
    ]
