# Generated by Django 3.1.2 on 2021-04-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210327_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicetoken',
            old_name='consumer_id',
            new_name='consumer',
        ),
    ]
